__descr__ = 'BCacheFS tools'
__version__ = '0.0.0'
__license__ = 'BSD 3-Clause License'
__author__ = u'Pierre Delaunay'
__author_email__ = 'setepenre@outlook.com'
__copyright__ = u'2021 Pierre Delaunay'
__url__ = 'https://github.com/Delaunay/bcachefs-pytools'
