name: tests

on: [push]


jobs:
  pybcachefs-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt install gcc meson ninja-build
        sudo apt install make pkg-config libaio-dev libblkid-dev\
            libkeyutils-dev liblz4-dev libscrypt-dev libsodium-dev\
            liburcu-dev libzstd-dev libudev-dev uuid-dev zlib1g-dev\
            libfuse3-dev
        
        python setup.py install

    - name: tests
      run: |
        ./tests/check.bash
